import type { Drink } from './types'

export const PRESET_DRINKS: Drink[] = [
  {
    id: 'golden-hour-oat-latte',
    name: 'Golden Hour Oat Latte',
    size: 'Grande',
    temperature: 'Hot',
    base: 'Espresso',
    milk: 'Oat Milk',
    syrups: [{ syrup: 'Vanilla', pumps: 2 }],
    iceLevel: 'No Ice',
    toppings: ['Cold Foam'],
    drizzles: ['Caramel Drizzle'],
    extras: ['Extra Shot'],
    charm: '🌸',
    createdAt: Date.now(),
  },
  {
    id: 'emerald-matcha-cloud',
    name: 'Emerald Matcha Cloud',
    size: 'Venti',
    temperature: 'Blended',
    base: 'Matcha',
    milk: 'Coconut Milk',
    syrups: [{ syrup: 'Lavender', pumps: 1 }],
    iceLevel: 'Regular Ice',
    toppings: ['Sweet Cream'],
    drizzles: ['Honey'],
    extras: ['Protein Powder'],
    charm: '🍃',
    createdAt: Date.now(),
  },
  {
    id: 'midnight-mocha-storm',
    name: 'Midnight Mocha Storm',
    size: 'Venti',
    temperature: 'Iced',
    base: 'Frappuccino Base',
    milk: 'Whole Milk',
    syrups: [{ syrup: 'White Mocha', pumps: 3 }],
    iceLevel: 'Regular Ice',
    toppings: ['Whipped Cream', 'Chocolate Chips'],
    drizzles: ['Mocha Drizzle'],
    extras: ['Salted Caramel Bits'],
    charm: '🌙',
    createdAt: Date.now(),
  },
  {
    id: 'strawberry-sunrise-refresher',
    name: 'Strawberry Sunrise Refresher',
    size: 'Grande',
    temperature: 'Iced',
    base: 'Refresher',
    milk: 'None',
    syrups: [{ syrup: 'Raspberry', pumps: 2 }],
    iceLevel: 'Light Ice',
    toppings: ['Matcha Powder'],
    drizzles: ['Honey'],
    extras: ['Decaf'],
    charm: '🍓',
    createdAt: Date.now(),
  },
  {
    id: 'caramel-velvet-macchiato',
    name: 'Caramel Velvet Macchiato',
    size: 'Grande',
    temperature: 'Hot',
    base: 'Espresso',
    milk: '2% Milk',
    syrups: [{ syrup: 'Caramel', pumps: 2 }],
    iceLevel: 'No Ice',
    toppings: ['Whipped Cream'],
    drizzles: ['Caramel Drizzle'],
    extras: ['Vanilla Sweet Cream'],
    charm: '⭐',
    createdAt: Date.now(),
  },
]
